// Manage Collection
export const CHOOSE_COLLECTION_CARDS = "CHOOSE_COLLECTION_CARDS"; // equiv to 'checked'
export const REMOVE_CHOSEN_COLLECTION = "REMOVE_CHOSEN_COLLECTION";
export const REMOVE_CHOSEN_COLLECTION_SUCCESS =
  "REMOVE_CHOSEN_COLLECTION_SUCCESS";
export const REMOVE_CHOSEN_COLLECTION_FAIL = "REMOVE_CHOSEN_COLLECTION_FAIL";
